-- =============================================
-- SIMPLE SCALAR FUNCTIONS
-- Definition:
-- Functions with parameters return a single value based on input.
-- =============================================

-- 1. Create a function to return the total stock value of a product (UnitPrice * UnitsInStock) given ProductID.

-- 2. Create a function to return the total orders placed by a customer (CustomerID).

-- 3. Create a function to return the total quantity of a product ordered (ProductID).

-- 4. Create a function to return the remaining stock after orders for a product.

-- 5. Create a function to return the average unit price of products in a category (CategoryID).

-- 6. Create a function to return the maximum unit price in a category.

-- 7. Create a function to return the minimum unit price in a category.

-- 8. Create a function to return total discontinued products in a category.

-- 9. Create a function to return the total number of suppliers in a country.

-- 10. Create a function to return the number of customers in a city.

-- 11. Create a function to return total products supplied by a supplier (SupplierID).

-- 12. Create a function to return total units on order for a product.

-- 13. Create a function to return the stock status (IN STOCK/OUT OF STOCK) for a product.

-- 14. Create a function to return the total quantity of orders handled by an employee (EmployeeID).

-- 15. Create a function to return the number of orders shipped by a specific shipper (ShipperID).

-- 16. Create a function to return total stock value in a category.

-- 17. Create a function to return the total orders in a date range (StartDate, EndDate).

-- 18. Create a function to return the full name of an employee (concatenate FirstName + LastName) given EmployeeID.

-- 19. Create a function to return the country of a customer given CustomerID.

-- 20. Create a function to return total products in stock for a supplier.

-- =============================================
-- STRING FUNCTIONS WITH PARAMETERS
-- =============================================

-- 21. Create a function to return the first N characters of a product name (ProductID, N).

-- 22. Create a function to return the last N characters of a product name.

-- 23. Create a function to convert the product name to UPPERCASE given ProductID.

-- 24. Create a function to convert the product name to lowercase.

-- 25. Create a function to return the length of a product name.

-- 26. Create a function to return a product name with a keyword replaced (parameters ProductID, OldText, NewText).

-- 27. Create a function to return a concatenated string of product name and category name.

-- 28. Create a function to return the first N characters of customer’s city.

-- 29. Create a function to return the last N characters of employee’s last name.

-- 30. Create a function to return the country and city concatenated for a customer.

-- =============================================
-- AGGREGATION & CALCULATION FUNCTIONS
-- =============================================

-- 31. Create a function to return total quantity ordered for a product category.

-- 32. Create a function to return total revenue generated by a product (UnitPrice * Quantity).

-- 33. Create a function to return the average order quantity for a product.

-- 34. Create a function to return total quantity of products ordered by a customer.

-- 35. Create a function to return total stock value per supplier.

-- 36. Create a function to return the highest quantity ordered in an order.

-- 37. Create a function to return the lowest quantity ordered in an order.

-- 38. Create a function to return total quantity of products on order across all products.

-- 39. Create a function to return total stock value for discontinued products.

-- 40. Create a function to return average UnitsInStock for a category.

-- =============================================
-- CONDITIONAL & PARAMETERIZED FUNCTIONS
-- =============================================

-- 41. Create a function to return 'High Stock' if UnitsInStock > 50 else 'Low Stock' for a product.

-- 42. Create a function to return 'Expensive' if UnitPrice > 20 else 'Affordable'.

-- 43. Create a function to return 1 if a customer has placed any orders, else 0.

-- 44. Create a function to return 1 if a product is discontinued, else 0.

-- 45. Create a function to return 'Available' if UnitsInStock > ReorderLevel, else 'Reorder Needed'.

-- 46. Create a function to return 'Active Supplier' if supplier supplies more than 5 products.

-- 47. Create a function to return a category name given CategoryID.

-- 48. Create a function to return the shipper name given ShipperID.

-- 49. Create a function to return the total orders in a given month and year (parameters Month, Year).

-- 50. Create a function to return the number of products whose unit price falls between two values (MinPrice, MaxPrice).
