-- =============================================
-- WINDOW FUNCTIONS: PARTITION BY PRACTICE
-- Using SUM(), COUNT(), AVG(), MAX(), MIN(), etc. with PARTITION BY
-- =============================================

-- 1. Show each order along with the total order amount per customer (SUM() OVER(PARTITION BY CustomerID)).

-- 2. For each employee, list all orders handled + total number of orders handled by that employee.

-- 3. Display each product with total ordered quantity + total quantity sold per category.

-- 4. For each supplier, list products + average UnitPrice for that supplier.

-- 5. For each category, list products + maximum UnitPrice inside the category.

-- 6. Show each customer’s orders + latest order date per customer.

-- 7. For each product, show all order_details + total revenue generated by that product.

-- 8. For each shipper, list orders shipped + count of orders shipped by that shipper.

-- 9. For each employee, show all orders + sum of all order amounts handled by that employee.

-- 10. For each category, display products + minimum UnitsInStock for that category.

-- 11. List suppliers and their products + supplier-wise total number of products supplied.

-- 12. For each customer, list orders + customer’s average order amount.

-- 13. For each product, show all orders + maximum quantity ordered for that product.

-- 14. For each order, list order_details + total items ordered within that order.

-- 15. For each customer, show orders + customer-wise order count.

-- 16. For each category, show all products + sum of UnitsOnOrder in that category.

-- 17. For each employee, list orders + minimum order value handled by that employee.

-- 18. For each supplier, show products + total UnitsInStock per supplier.

-- 19. For each product, list order_details + average quantity ordered for that product.

-- 20. For each country, show customers + total number of customers in that country.

-- 21. For each category, show products + average product price in that category.

-- 22. For each customer, show orders + highest order amount ever placed.

-- 23. For each shipper, list orders + total freight cost shipped by that shipper.

-- 24. For each order, show order_details + maximum discount applied in the order (if discount column exists).

-- 25. For each employee, display orders + employee-wise average order amount.

-- 26. For each supplier, list products + maximum UnitsOnOrder for products supplied by that supplier.

-- 27. For each category, show products + total number of products in that category.

-- 28. For each customer, list orders + count of distinct products ordered (using COUNT() OVER + PARTITION BY).

-- 29. For each employee, show orders + employee-wise last order date.

-- 30. For each customer, show every order + customer’s total quantity ordered across all orders.
